### ISSUE TITLE
bitcraft

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#19]
I'd love to see littleBits Minecraft mod added: http://littlebits.cc/bitcraft

**Comment by chimericdream** [comment]
Apparently they haven't updated it in awhile, so it only supports 1.7.10. [I made an issue](https://github.com/littlebits/bitCraft/issues/4) on their repo asking of they plan to update.

It's also not currently in the Curse launcher, or even on their list of allowed third-party mods. But you can suggest mods to add to the list, so I did that. Not sure they'll accept it, though. It looks like the only way to download a compiled version of the mod is the Technic launcher. Otherwise, you have to pull it down and compile it yourself. We'll see.

**Comment by chimericdream** [comment]
I'm closing the issue for now, but I added it to the project board in the backlog to keep it visible. If/when the mod is updated and added to the allowed third-party list in Curse, we can re-open it.
